spring.application.name=catalog-service
spring.config.import=optional:configserver:http://localhost:8081
spring.datasource.url=jdbc:postgresql://192.168.0.61:5432/cubixkhzr
spring.datasource.username=webuser
spring.datasource.password=psoestrg

