server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  cubixwebshop:
    tokenlib:
      keypaths:
        public: /home/koszegig/webshop/public.pem
        private: /home/koszegig/webshop/private.pem
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /api$\{segment}
        - id: flights
          uri: lb://flights
          predicates:
            - Path=/catalogs/**
          filters:
            - RewritePath=/catalog-service(?<segment>/?.*), /api$\{segment}