server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  cubixwebshop:
    tokenlib:
      keypaths:
        private: /home/koszegig/webshop/private.pem
        public: /home/koszegig/webshop/public.pem
